import { Command } from "commander";
import * as path from "path";
import * as fs from "fs/promises";
import YAML from "yaml";
import {
  OPENVIBER_DIR,
  CONFIG_FILE,
  getViberId,
  formatSkillHealthReport,
  loadSavedConfig,
} from "../common";
import { loadSettings, saveSettings } from "../../skills/hub/settings";

export const onboardCommand = new Command("onboard")
  .description("Set up OpenViber on this machine (use --token to connect to OpenViber Web)")
  .option("-t, --token <token>", "Onboard token from OpenViber Web (connect mode)")
  .option("--gateway <url>", "Gateway URL override (default: auto from web)")
  .option("--board <url>", "(deprecated: use --gateway) Gateway URL override")
  .option("--hub <url>", "(deprecated: use --gateway) Gateway URL override")
  .option("--no-interactive", "Skip interactive prompts (just scaffold and show health report)")
  .action(async (options) => {
    const configDir = OPENVIBER_DIR;
    const vibersDir = path.join(configDir, "vibers");
    const skillsDir = path.join(configDir, "skills");

    console.log(`
+-------------------------------------------------------+
|               OPENVIBER SETUP                           |
+-------------------------------------------------------+
`);

    // Create directories
    console.log("Creating directories...");
    await fs.mkdir(configDir, { recursive: true });
    await fs.mkdir(vibersDir, { recursive: true });
    await fs.mkdir(skillsDir, { recursive: true });
    console.log(`  ✓ ${configDir}`);
    console.log(`  ✓ ${vibersDir}`);
    console.log(`  ✓ ${skillsDir}`);

    // ===== Connected mode: onboard with token =====
    if (options.token) {
      console.log("\nConnecting to OpenViber Web...");

      // Determine the web URL to call
      const webBaseUrl = options.gateway || options.board || options.hub || process.env.OPENVIBER_WEB_URL || "http://localhost:6006";

      try {
        const response = await fetch(`${webBaseUrl}/api/vibers/onboard`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ token: options.token }),
        });

        if (!response.ok) {
          const err = await response.json().catch(() => ({ error: "Unknown error" }));
          console.error(`\n  ✗ Onboarding failed: ${err.error || "Invalid or expired token"}`);
          console.error("\n  Create a new viber node on the web and try again.");
          process.exit(1);
        }

        const data = await response.json() as {
          ok: boolean;
          viberId: string;
          name: string;
          authToken: string;
          config: Record<string, unknown>;
        };

        // Determine the board server WebSocket URL from the web URL
        const gatewayWsUrl = (options.gateway || options.board || options.hub)
          ? (options.gateway || options.board || options.hub).replace(/^http/, "ws") + "/ws"
          : webBaseUrl.replace(/^http/, "ws").replace(":6006", ":6007") + "/ws";

        // Save config for future `openviber start` calls
        const savedConfig = {
          mode: "connected",
          viberId: data.viberId,
          name: data.name,
          gatewayUrl: gatewayWsUrl,
          boardUrl: gatewayWsUrl, // deprecated compat
          hubUrl: gatewayWsUrl, // deprecated compat
          authToken: data.authToken,
          webUrl: webBaseUrl,
          onboardedAt: new Date().toISOString(),
        };

        await fs.writeFile(
          CONFIG_FILE,
          `# OpenViber Config — auto-generated by 'openviber onboard --token'
# Do not edit manually. Manage your viber at ${webBaseUrl}
${YAML.stringify(savedConfig)}`,
        );

        console.log(`  ✓ Connected to ${webBaseUrl}`);
        console.log(`  ✓ Viber: ${data.name} (${data.viberId.slice(0, 8)}...)`);
        console.log(`  ✓ Config saved to ${CONFIG_FILE}`);

      } catch (error: any) {
        console.error(`\n  ✗ Failed to connect: ${error.message}`);
        console.error(`\n  Make sure the OpenViber web is running at ${options.gateway || options.board || options.hub || "http://localhost:6006"}.`);
        process.exit(1);
      }
    } else {
      // ===== Standalone mode: local-only setup =====
      console.log("Setting up standalone mode (local-only)...");

      // Save standalone config
      const savedConfig = {
        mode: "standalone",
        onboardedAt: new Date().toISOString(),
      };

      try {
        await fs.access(CONFIG_FILE);
        console.log(`\n  ⏭ config.yaml already exists, skipping`);
      } catch {
        await fs.writeFile(
          CONFIG_FILE,
          `# OpenViber Config — standalone mode\n# To connect to OpenViber Web, re-run: openviber onboard --token <token>\n${YAML.stringify(savedConfig)}`,
        );
        console.log(`  ✓ Created config.yaml (standalone mode)`);
      }
    }

    // Scaffold viber files (both modes)
    const defaultViberPath = path.join(configDir, "viber.yaml");
    try {
      await fs.access(defaultViberPath);
      console.log(`\n  ⏭ viber.yaml already exists, skipping`);
    } catch {
      const defaultViber = `# Default Viber Configuration
name: default
description: General-purpose assistant

# LLM Provider (openrouter recommended for multi-model access)
provider: openrouter
model: anthropic/claude-sonnet-4-20250514

# System prompt
systemPrompt: |
  You are a helpful AI assistant running on the user's local machine.
  You have access to files, terminal, and browser tools.
  Be concise and helpful.

# Tools available to this viber
tools:
  - file
  - terminal
  - browser

# Working mode: "always-ask" | "viber-decides" | "always-execute"
workingMode: viber-decides
`;
      await fs.writeFile(defaultViberPath, defaultViber);
      console.log(`\n  ✓ Created viber.yaml`);
    }

    // Create USER.md (shared across vibers)
    const userMdPath = path.join(configDir, "USER.md");
    try {
      await fs.access(userMdPath);
    } catch {
      await fs.writeFile(userMdPath, "# User Context\n\nDescribe who you are and what you're working on.\n");
      console.log(`  ✓ Created USER.md`);
    }

    // Create IDENTITY.md (shared across vibers)
    const identityMdPath = path.join(configDir, "IDENTITY.md");
    try {
      await fs.access(identityMdPath);
    } catch {
      await fs.writeFile(identityMdPath, "# Identity\n\nDefine the identity of this machine or deployment.\n");
      console.log(`  ✓ Created IDENTITY.md`);
    }

    // Create per-viber SOUL.md and MEMORY.md
    const defaultViberDir = path.join(vibersDir, "default");
    await fs.mkdir(defaultViberDir, { recursive: true });

    const soulPath = path.join(defaultViberDir, "SOUL.md");
    try {
      await fs.access(soulPath);
    } catch {
      await fs.writeFile(soulPath, "# Soul\n\nDefine this viber's personality and communication style.\n");
      console.log(`  ✓ Created vibers/default/SOUL.md`);
    }

    const memoryPath = path.join(defaultViberDir, "MEMORY.md");
    try {
      await fs.access(memoryPath);
    } catch {
      await fs.writeFile(memoryPath, "# Memory\n\nLong-term notes and context.\n");
      console.log(`  ✓ Created vibers/default/MEMORY.md`);
    }

    // Generate viber ID
    const viberId = await getViberId();

    // Load any previously saved API keys from ~/.openviber/.env
    const { loadOpenViberEnv, runOnboardingWizard } = await import("../auth");
    await loadOpenViberEnv();

    // Interactive onboarding wizard (LLM key, skill picker, skill setup)
    // or passive health report with --no-interactive
    let selectedSkills: string[] = [];

    if (options.interactive === false) {
      // Non-interactive: just show the health report (legacy behavior)
      try {
        const { getSkillHealthReport } = await import("../../skills/health");
        const report = await getSkillHealthReport();
        const lines = formatSkillHealthReport(report);
        if (lines.length > 0) {
          console.log(lines.join("\n"));
        }
      } catch (err: any) {
        console.warn(
          `[onboard] Skill health check failed: ${err?.message || String(err)}`,
        );
      }
    } else {
      // Interactive: full wizard
      try {
        selectedSkills = await runOnboardingWizard();

        // Save selected skills to settings.yaml
        if (selectedSkills.length > 0) {
          const settings = await loadSettings();
          settings.standaloneSkills = Array.from(
            new Set([...(settings.standaloneSkills || []), ...selectedSkills]),
          );
          await saveSettings(settings);
        }
      } catch (err: any) {
        console.warn(
          `[onboard] Interactive setup failed: ${err?.message || String(err)}`,
        );
        // Fall back to passive health report
        try {
          const { getSkillHealthReport } = await import("../../skills/health");
          const report = await getSkillHealthReport();
          const lines = formatSkillHealthReport(report);
          if (lines.length > 0) {
            console.log(lines.join("\n"));
          }
        } catch {
          // ignore
        }
      }
    }

    const mode = options.token ? "connected" : "standalone";
    const nextCmd = options.token
      ? "openviber start"
      : "openviber start  (or: openviber run \"Hello!\")";
    const connectHint = options.token
      ? ""
      : "\n  To connect to OpenViber Web later:\n     openviber onboard --token <token-from-web>\n";

    console.log(`
────────────────────────────────────────────────────────────
Setup complete! (${mode} mode)

Your viber ID: ${viberId}
Config directory: ${configDir}

Next step:
  ${nextCmd}
${connectHint}
────────────────────────────────────────────────────────────
`);
  });
